// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64
	Uuid      string
	Name      string
	Github    sql.NullString
	Twitter   sql.NullString
	Mastodon  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
